USE VENDAS_SUCOS;

CREATE TABLE FATURAMENTO
(DATA_VENDA DATE NULL, TOTAL_VENDA FLOAT);

DELIMITER //
CREATE TRIGGER TG_CALCULO_FATURAMENTO_INSERT AFTER INSERT ON ITENS_NOTAS
FOR EACH ROW
BEGIN
	DELETE FROM FATURAMENTO;
    INSERT INTO FATURAMENTO
	SELECT `DATA` AS DATA_VENDA, SUM(QUANTIDADE * PRECO) AS TOTAL_VENDA FROM
    NOTAS A INNER JOIN ITENS_NOTAS B
    GROUP BY `DATA`;
END//

SELECT * FROM FATURAMENTO;

DELIMITER //
CREATE TRIGGER TG_UPDATE_IDADE BEFORE INSERT ON CLIENTES
FOR EACH ROW
BEGIN
    SET NEW.IDADE = TIMESTAMPDIFF(YEAR, NEW.DATA_NASCIMENTO, NOW());
END //

SELECT * FROM CLIENTES;


DELIMITER //
CREATE TRIGGER TG_CALCULO_FATURAMENTO_UPDATE AFTER UPDATE ON ITENS_NOTAS
FOR EACH ROW
BEGIN
	DELETE FROM FATURAMENTO;
    INSERT INTO FATURAMENTO
	SELECT `DATA` AS DATA_VENDA, SUM(QUANTIDADE * PRECO) AS TOTAL_VENDA FROM
    NOTAS A INNER JOIN ITENS_NOTAS B
    GROUP BY `DATA`;
END//

DELIMITER //
CREATE TRIGGER TG_CALCULO_FATURAMENTO_DELETE AFTER DELETE ON ITENS_NOTAS
FOR EACH ROW
BEGIN
	DELETE FROM FATURAMENTO;
    INSERT INTO FATURAMENTO
	SELECT `DATA` AS DATA_VENDA, SUM(QUANTIDADE * PRECO) AS TOTAL_VENDA FROM
    NOTAS A INNER JOIN ITENS_NOTAS B
    GROUP BY `DATA`;
END//

INSERT INTO NOTAS (NUMERO, `DATA`, CPF, MATRICULA, IMPOSTO)
VALUES ('0107', '2019-05-08', '1471156710' , '235', 0.10);

INSERT INTO ITENS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('0107', '1000889', 100, 10);

INSERT INTO ITENS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('0107', '1002334', 100, 10);
SELECT * FROM FATURAMENTO;

UPDATE ITENS_NOTAS SET QUANTIDADE = 400
WHERE NUMERO = '0107' AND CODIGO = '1002334';
SELECT * FROM FATURAMENTO;

DELETE FROM ITENS_NOTAS WHERE NUMERO = '0107' AND CODIGO = '1002334';
SELECT * FROM FATURAMENTO;