USE sucos_vendas;


DROP procedure IF EXISTS Limite_Creditos;
DELIMITER $$
CREATE PROCEDURE Limite_Creditos ()
BEGIN
	DECLARE vLIMITE_TOTAL FLOAT DEFAULT 0;
    DECLARE vLIMITE FLOAT;
    DECLARE FIM_DO_CURSOR INT DEFAULT 0;
    DECLARE c CURSOR FOR SELECT LIMITE_DE_CREDITO FROM TABELA_DE_CLIENTES;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM_DO_CURSOR = 1;
    
    OPEN c;
    WHILE FIM_DO_CURSOR = 0 DO
		FETCH c INTO vLIMITE;
        IF FIM_DO_CURSOR = 0 THEN
			SET vLIMITE_TOTAL = vLIMITE_TOTAL + vLIMITE;
			SELECT vLIMITE, vLIMITE_TOTAL;
		END IF;
    END WHILE;
    CLOSE c;
    
    SELECT vLIMITE_TOTAL AS LIMITE_TOTAL_DOS_CLIENTES;
END$$
DELIMITER ;

CALL Limite_Creditos ();

DROP procedure IF EXISTS Mais_Um_Campo;
DELIMITER $$
CREATE PROCEDURE Mais_Um_Campo()
BEGIN
	DECLARE vFATURAMENTO DECIMAL(15,5) DEFAULT 0;
    DECLARE vQUANTIDADE, vPRECO DECIMAL(10,5);
    DECLARE FIM_DO_CURSOR INT DEFAULT 0;
    DECLARE c CURSOR FOR SELECT B.QUANTIDADE,B.PRECO FROM 
    notas_fiscais A INNER JOIN itens_notas_fiscais B
    ON A.NUMERO = B.NUMERO
    WHERE YEAR(A.DATA_VENDA) = 2017 AND MONTH(A.DATA_VENDA) = 1;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM_DO_CURSOR = 1;
    
    OPEN c;
    CALCULO_FATURAMENTO: LOOP
		FETCH c INTO vQUANTIDADE, vPRECO;
        IF FIM_DO_CURSOR = 1 THEN
			LEAVE CALCULO_FATURAMENTO;
		END IF;
        SET vFATURAMENTO = vFATURAMENTO + (vQUANTIDADE * vPRECO);
	END LOOP CALCULO_FATURAMENTO;
    CLOSE c;
    
    SELECT vFATURAMENTO AS FATURAMENTO_TOTAL;
END$$
DELIMITER ;

CALL Mais_Um_Campo();