USE SUCOS_VENDAS;

DROP FUNCTION IF EXISTS Quantidade_Notas;
DELIMITER $$
CREATE FUNCTION Quantidade_Notas(DATA_ESCOLHIDA DATE)
RETURNS INT
BEGIN
	DECLARE NUMNOTAS INT;
    
	SELECT COUNT(*) INTO NUMNOTAS FROM notas_fiscais 
    WHERE DATA_VENDA = DATA_ESCOLHIDA;
    
    RETURN NUMNOTAS;
END$$
DELIMITER ;

SELECT Quantidade_Notas('20170101') AS TOTAL_NOTAS;