USE SUCOS_VENDAS;

DROP PROCEDURE IF EXISTS Testa_Numero_Notas;
DELIMITER $$
CREATE PROCEDURE Testa_Numero_Notas(vDATA_VENDA DATE)
BEGIN
	DECLARE vNUM_NOTAS INT DEFAULT 65;
    DECLARE vSITUACAO_NOTAS VARCHAR(10);
    
	SELECT COUNT(*) INTO vNUM_NOTAS
    FROM notas_fiscais
    WHERE DATA_VENDA = vDATA_VENDA;
    
    IF vNUM_NOTAS > 70 THEN
		SET vSITUACAO_NOTAS = 'Muita nota';
	ELSE
		SET vSITUACAO_NOTAS = 'Pouca nota';
	END IF;
    
    SELECT vNUM_NOTAS, vSITUACAO_NOTAS;
END $$
DELIMITER ;

CALL Testa_Numero_Notas('20170501');


DROP PROCEDURE IF EXISTS Comparativo_Vendas;
DELIMITER $$
CREATE PROCEDURE Comparativo_Vendas(vPRIMEIRA_DATA DATE, vSEGUNDA_DATA DATE)
BEGIN
	DECLARE vVENDAS_PRIMEIRA_DATA, vVENDAS_SEGUNDA_DATA DECIMAL(10,2);
    DECLARE vCOMPARACAO DECIMAL(3,2);
    DECLARE vSITUACAO_VENDAS VARCHAR(8);
    
    SELECT SUM(B.QUANTIDADE * B.PRECO) INTO vVENDAS_PRIMEIRA_DATA FROM
    notas_fiscais A INNER JOIN itens_notas_fiscais B
    ON A.NUMERO = B.NUMERO 
    WHERE A.DATA_VENDA = vPRIMEIRA_DATA;
    
    SELECT SUM(B.QUANTIDADE * B.PRECO) INTO vVENDAS_SEGUNDA_DATA FROM
    notas_fiscais A INNER JOIN itens_notas_fiscais B
    ON A.NUMERO = B.NUMERO 
    WHERE A.DATA_VENDA = vSEGUNDA_DATA;
    
    SET vCOMPARACAO = (vVENDAS_SEGUNDA_DATA/vVENDAS_PRIMEIRA_DATA) - 1;
    
    IF vCOMPARACAO > 0.10 THEN
		SET vSITUACAO_VENDAS = 'Verde';
	ELSEIF vCOMPARACAO > -0.10 THEN
		SET vSITUACAO_VENDAS = 'Amarela';
	ELSE
		SET vSITUACAO_VENDAS = 'Vermelha';
    end if;
    
    select vVENDAS_PRIMEIRA_DATA AS PRIMEIRA_DATA,vVENDAS_SEGUNDA_DATA AS SEGUNDA_DATA, vSITUACAO_VENDAS AS SITUACAO;
END$$

CALL Comparativo_Vendas('20170101','20180101');