USE SUCOS_VENDAS;

DROP PROCEDURE IF EXISTS UPDATE_IDADE_CLIENTES;
DELIMITER $$
CREATE PROCEDURE UPDATE_IDADE_CLIENTES()
BEGIN
	UPDATE TABELA_DE_CLIENTES
    SET IDADE = TIMESTAMPDIFF(YEAR,DATA_DE_NASCIMENTO,CURDATE());
END$$
DELIMITER ;

SELECT CPF, NOME, DATA_DE_NASCIMENTO, IDADE FROM tabela_de_clientes;

CALL UPDATE_IDADE_CLIENTES();

SELECT CPF, NOME, DATA_DE_NASCIMENTO, IDADE FROM tabela_de_clientes;

DROP PROCEDURE IF EXISTS Reajuste_Comissao;
DELIMITER $$
CREATE PROCEDURE Reajuste_Comissao(REAJUSTE FLOAT)
BEGIN
	UPDATE TABELA_DE_VENDEDORES
    SET PERCENTUAL_COMISSAO = PERCENTUAL_COMISSAO * (1 + REAJUSTE);
END$$
DELIMITER ;

SELECT MATRICULA, NOME, PERCENTUAL_COMISSAO FROM TABELA_DE_VENDEDORES;

CALL Reajuste_Comissao(0.80);

SELECT MATRICULA, NOME, PERCENTUAL_COMISSAO FROM TABELA_DE_VENDEDORES;


DROP PROCEDURE IF EXISTS Quantidade_Notas;
DELIMITER $$
CREATE PROCEDURE Quantidade_Notas(DATA_ESCOLHIDA DATE)
BEGIN
	DECLARE NUMNOTAS INT;
    
	SELECT COUNT(*) INTO NUMNOTAS FROM notas_fiscais 
    WHERE DATA_VENDA = DATA_ESCOLHIDA
    GROUP BY DATA_VENDA;
    
    SELECT NUMNOTAS AS NUMERO_DE_NOTAS;
END$$
DELIMITER ;

CALL Quantidade_Notas('2017-01-01');