
SELECT CURRENT_TIMESTAMP() AS RESULTADO;

SELECT CONCAT('O dia de hoje é : ', CURRENT_TIMESTAMP()) AS RESULTADO;

SELECT CONCAT('O dia de hoje é : ', 
DATE_FORMAT(CURRENT_TIMESTAMP(),'%W, %d/%m/%Y - %U') ) AS RESULTADO;

SELECT SUBSTRING(CONVERT(23.3, CHAR),1,1) AS RESULTADO;

SELECT NOME, YEAR(DATA_VENDA) AS ANO, ROUND(SUM(QUANTIDADE * PRECO)) AS FATURA
FROM tabela_de_clientes A INNER JOIN notas_fiscais B
ON A.CPF = B.CPF
INNER JOIN itens_notas_fiscais C
ON B.NUMERO = C.NUMERO
GROUP BY NOME, ANO
HAVING ANO = 2016;

SELECT A.NOME, YEAR(B.DATA_VENDA) AS ANO, ROUND(SUM(C.QUANTIDADE * C.PRECO)) AS FATURA
FROM tabela_de_clientes A INNER JOIN notas_fiscais B
ON A.CPF = B.CPF
INNER JOIN itens_notas_fiscais C
ON B.NUMERO = C.NUMERO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY NOME, ANO;

SELECT A.NOME, 
CONCAT('Cliente ', A.NOME,
' faturou ', ROUND(SUM(C.QUANTIDADE * C.PRECO)), 
' no ano de ', YEAR(B.DATA_VENDA)) AS SENTENCA,
YEAR(B.DATA_VENDA) AS ANO, 
ROUND(SUM(C.QUANTIDADE * C.PRECO)) AS FATURA
FROM tabela_de_clientes A INNER JOIN notas_fiscais B
ON A.CPF = B.CPF
INNER JOIN itens_notas_fiscais C
ON B.NUMERO = C.NUMERO
GROUP BY NOME, ANO
HAVING ANO = 2016;

SELECT A.NOME, 
CONCAT('Cliente ', A.NOME,
' faturou ', CAST(ROUND(SUM(C.QUANTIDADE * C.PRECO)) AS CHAR(20)), 
' no ano de ', CAST(YEAR(B.DATA_VENDA) AS CHAR(4))) AS SENTENCA,
YEAR(B.DATA_VENDA) AS ANO, 
ROUND(SUM(C.QUANTIDADE * C.PRECO)) AS FATURA
FROM tabela_de_clientes A INNER JOIN notas_fiscais B
ON A.CPF = B.CPF
INNER JOIN itens_notas_fiscais C
ON B.NUMERO = C.NUMERO
GROUP BY NOME, ANO
HAVING ANO = 2016;