USE sakila;
TRUNCATE TABLE DEFAULT_TABLE2;
DROP TABLE IF EXISTS DEFAULT_TABLE;
CREATE TABLE DEFAULT_TABLE (ID INTEGER AUTO_INCREMENT, NOME VARCHAR(100), PRIMARY KEY(ID));
ALTER TABLE DEFAULT_TABLE ENGINE = MyISAM;

SELECT * FROM DEFAULT_TABLE;

INSERT INTO DEFAULT_TABLE(NOME)
SELECT CODIGO_DO_PRODUTO FROM sucos_vendas.itens_notas_fiscais
LIMIT 10000;

SELECT * FROM DEFAULT_TABLE;

DROP TABLE IF EXISTS DEFAULT_TABLE2;
CREATE TABLE DEFAULT_TABLE2 (ID INTEGER AUTO_INCREMENT, NOME VARCHAR(100), PRIMARY KEY(ID)) ENGINE = MEMORY;

SELECT * FROM DEFAULT_TABLE2;

INSERT INTO DEFAULT_TABLE2(NOME)
SELECT CODIGO_DO_PRODUTO FROM sucos_vendas.itens_notas_fiscais
LIMIT 10000;

SELECT * FROM DEFAULT_TABLE2;




